# Generated by Django 4.2.20 on 2025-04-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_recipe_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
