# Generated by Django 4.2.20 on 2025-04-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
